$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Accept", "application/json, text/plain, */*")
$headers.Add("Accept-Encoding", "gzip, deflate, br, zstd")
$headers.Add("Accept-Language", "en")
$headers.Add("Authorization", "%s")
$headers.Add("Content-Length", "4")
$headers.Add("Content-Type", "application/json")
$headers.Add("Dnt", "1")
$headers.Add("Origin", "https://myaccount.contact.co.nz")
$headers.Add("Priority", "u=1, i")
$headers.Add("Referer", "https://myaccount.contact.co.nz/")
$headers.Add("Sec-Ch-Ua", "`"Not/A)Brand`";v=`"8`", `"Chromium`";v=`"126`", `"Google Chrome`";v=`"126`"")
$headers.Add("Sec-Ch-Ua-Mobile", "?0")
$headers.Add("Sec-Ch-Ua-Platform", "`"Windows`"")
$headers.Add("Sec-Fetch-Dest", "empty")
$headers.Add("Sec-Fetch-Mode", "cors")
$headers.Add("Sec-Fetch-Site", "cross-site")
$headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
$headers.Add("X-Api-Key", "kbIthASA7e1M3NmpMdGrn2Yqe0yHcCjL4QNPSUij")
$headers.Add("X-Correlation-Id", "%s")
$headers.Add("X-Csrf-Token", "%s")
$response = Invoke-RestMethod '%s' -Method 'POST' -Headers $headers
$response | ConvertTo-Json
